name: Run and Display Output of All Root Files

on:
  push:
    branches:
      - main  # Jalankan workflow setiap ada push ke branch 'main'

jobs:
  run-all:
    runs-on: ubuntu-latest  # Jalankan workflow di server Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checkout kode dari repositori

    - name: Grant execute permissions for all files in the root directory
      run: chmod +x ./*  # Beri izin eksekusi pada semua file di root direktori

    - name: Run all executable files and display output
      run: |
        for file in $(ls -p | grep -v /); do  # Loop semua file di root direktori
          echo "Running $file..."  # Tampilkan nama file yang sedang dijalankan
          output=$(./$file)  # Simpan output dari eksekusi file
          echo "$output"  # Tampilkan hasil output di log
          if [ $? -ne 0 ]; then
            echo "Error running $file"  # Jika ada error, tampilkan pesan error
          fi
        done
